# Generated by Django 2.0.7 on 2018-07-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCTR',
            fields=[
                ('image_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('ctr', models.DecimalField(decimal_places=19, max_digits=20)),
                ('black_x', models.DecimalField(decimal_places=19, max_digits=20)),
                ('text', models.DecimalField(decimal_places=19, max_digits=20)),
                ('girl', models.DecimalField(decimal_places=19, max_digits=20)),
                ('headwear', models.DecimalField(decimal_places=19, max_digits=20)),
                ('poster', models.DecimalField(decimal_places=19, max_digits=20)),
                ('fun', models.DecimalField(decimal_places=19, max_digits=20)),
                ('skyblue', models.DecimalField(decimal_places=19, max_digits=20)),
            ],
        ),
    ]
